services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "34961:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: msqdb
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
  api:
    image: gradle:8.7.0-jdk21
    working_dir: /app
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:34961/msqdb
      - DATASOURCE_USERNAME=pgadmin
      - DATASOURCE_PASSWORD=pgadmin
    volumes:
      - ./workspace/musiqul-api:/app
    ports:
      - "34962:8080"
    command: ./gradlew clean bootRun -x test
  web:
    image: node:22
    working_dir: /app
    volumes:
      - ./workspace/musiqul-web:/app
    ports:
      - "34963:3000"
    command: >
      /bin/sh -c '
        npm install &&
        npm run dev
      '
volumes:
  db-data:
    name: db-data

